#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Generate .Rd files from roxygen2 comments in R/ directory.
This is a lightweight helper; for production use devtools::document().
"""
from __future__ import print_function
import os
import re
import glob
import io

R_DIR = os.path.join(os.path.dirname(__file__), "R")
MAN_DIR = os.path.join(os.path.dirname(__file__), "man")


def parse_roxygen(lines):
    """Extract roxygen blocks from R source lines."""
    blocks = []
    current = []
    in_roxygen = False
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("#'"):
            in_roxygen = True
            current.append(stripped[2:].lstrip())
        else:
            if in_roxygen:
                blocks.append(current)
                current = []
            in_roxygen = False
    if current:
        blocks.append(current)
    return blocks


def block_to_rd(block, func_name, usage_sig):
    """Convert a roxygen block to Rd content."""
    title = ""
    description = []
    params = []
    details = []
    return_val = ""
    examples = []
    exports = False

    i = 0
    while i < len(block):
        line = block[i]
        if line.startswith("@title "):
            title = line[7:].strip()
        elif line.startswith("@param "):
            rest = line[7:].strip()
            m = re.match(r'(\S+)\s+(.+)', rest)
            if m:
                params.append((m.group(1), m.group(2)))
            else:
                params.append((rest, ""))
        elif line.startswith("@return ") or line.startswith("@returns "):
            return_val = line.split(" ", 1)[1].strip()
        elif line.startswith("@details"):
            i += 1
            while i < len(block) and not block[i].startswith("@"):
                details.append(block[i])
                i += 1
            continue
        elif line.startswith("@examples"):
            i += 1
            while i < len(block) and not block[i].startswith("@"):
                examples.append(block[i])
                i += 1
            continue
        elif line.startswith("@export"):
            exports = True
        elif line.startswith("@"):
            pass
        elif not title:
            title = line
        else:
            description.append(line)
        i += 1

    if not exports:
        return None

    desc = "\n".join(description).strip()
    if not desc:
        desc = title

    rd = []
    rd.append(r"% Generated by generate_rd.py")
    rd.append(r"\name{" + func_name + "}")
    rd.append(r"\alias{" + func_name + "}")
    rd.append(r"\title{" + title + "}")
    rd.append(r"\description{")
    rd.append(desc)
    rd.append(r"}")

    if usage_sig:
        rd.append(r"\usage{")
        rd.append(usage_sig)
        rd.append(r"}")

    if params:
        rd.append(r"\arguments{")
        for pname, pdesc in params:
            rd.append(r"  \item{" + pname + "}{" + pdesc + "}")
        rd.append(r"}")

    if details:
        rd.append(r"\details{")
        rd.append("\n".join(details))
        rd.append(r"}")

    if return_val:
        rd.append(r"\value{")
        rd.append(return_val)
        rd.append(r"}")

    if examples:
        rd.append(r"\examples{")
        rd.append("\n".join(examples))
        rd.append(r"}")

    rd.append(r"\author{GeneLowPaper package}")
    rd.append("")
    return "\n".join(rd)


def extract_function_signatures(filepath):
    """Extract function name and signature from R file."""
    with io.open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    # Match function definition across multiple lines
    pattern = re.compile(
        r'^(\w+)\s*<-\s*function\s*\((.*?)\)\s*\{',
        re.MULTILINE | re.DOTALL
    )
    sigs = []
    for m in pattern.finditer(content):
        fname = m.group(1)
        args = m.group(2).replace("\n", " ").strip()
        # Clean extra spaces
        args = re.sub(r'\s+', ' ', args)
        sigs.append((fname, fname + "(" + args + ")"))
    return sigs


def main():
    if not os.path.exists(MAN_DIR):
        os.makedirs(MAN_DIR)

    r_files = glob.glob(os.path.join(R_DIR, "*.R"))
    for rf in r_files:
        with io.open(rf, "r", encoding="utf-8") as f:
            lines = f.readlines()

        blocks = parse_roxygen(lines)
        sigs = extract_function_signatures(rf)
        sig_map = {k: v for k, v in sigs}

        for block in blocks:
            # Find function name by looking for @name or infer from block position
            # We will match with signatures
            if not sigs:
                continue
            # Simple heuristic: use the first exported function in the file
            # that hasn't been processed yet.
            # Actually, we should pair blocks with signatures.
            # A more robust approach: look for @rdname or @name
            rdname = None
            for line in block:
                if line.startswith("@name "):
                    rdname = line[6:].strip()
                    break
                if line.startswith("@rdname "):
                    rdname = line[8:].strip()
                    break

            # For simplicity, assume each block corresponds to the next signature
            # This is a heuristic.
            pass

    # Better approach: just map each signature to its nearest preceding roxygen block
    for rf in r_files:
        with io.open(rf, "r", encoding="utf-8") as f:
            lines = f.readlines()

        # Find line numbers of function definitions and roxygen blocks
        sigs_info = []
        for i, line in enumerate(lines):
            m = re.match(r'^(\w+)\s*<-\s*function\s*\(', line)
            if m:
                sigs_info.append((i, m.group(1)))

        blocks_info = []
        start = None
        for i, line in enumerate(lines):
            stripped = line.lstrip()
            if stripped.startswith("#'"):
                if start is None:
                    start = i
            else:
                if start is not None:
                    blocks_info.append((start, i - 1))
                    start = None
        if start is not None:
            blocks_info.append((start, len(lines) - 1))

        # Pair blocks to nearest preceding function
        for fn_line, fname in sigs_info:
            block = None
            for s, e in reversed(blocks_info):
                if e < fn_line:
                    block = lines[s:e + 1]
                    break
            if block is None:
                continue
            block_text = [l.lstrip()[2:].lstrip() for l in block if l.lstrip().startswith("#'")]
            # Check if exported
            if "@export" not in "\n".join(block_text):
                continue
            # Build usage signature
            # Extract full signature from R code
            sig_text = ""
            depth = 0
            for j in range(fn_line, len(lines)):
                sig_text += lines[j]
                depth += lines[j].count("(") - lines[j].count(")")
                if depth <= 0 and ")" in lines[j]:
                    break
            sig_text = sig_text.strip()
            # Clean up
            sig_text = re.sub(r'\s+', ' ', sig_text.replace("\n", " "))
            sig_text = re.sub(r'^(\w+)\s*<-\s*function\s*', fname, sig_text)
            sig_text = re.sub(r'\{.*$', '', sig_text).strip()

            rd_content = block_to_rd(block_text, fname, sig_text)
            if rd_content:
                rd_path = os.path.join(MAN_DIR, fname + ".Rd")
                with io.open(rd_path, "w", encoding="utf-8") as outf:
                    outf.write(rd_content)
                print("Generated:", rd_path)


if __name__ == "__main__":
    main()
